# Generated by Django 3.2.5 on 2021-07-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fam_name', models.CharField(max_length=80)),
                ('Fam_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
