# Generated by Django 3.2.5 on 2021-07-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0002_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='Start_Date',
            field=models.CharField(max_length=20),
        ),
    ]
