# Generated by Django 3.2.5 on 2021-07-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0003_alter_records_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='Start_Date',
        ),
    ]
