# Generated by Django 3.2.5 on 2021-07-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0004_remove_records_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='Start_Date_A',
            field=models.DateField(auto_now=True),
        ),
    ]
