# Generated by Django 3.2.5 on 2021-07-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0006_remove_records_start_date_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='Rec_Type',
            new_name='test',
        ),
    ]
