# Generated by Django 3.2.5 on 2021-07-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0007_rename_rec_type_records_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='test1',
            field=models.CharField(default='mm_yyyy', max_length=10),
        ),
    ]
