# Generated by Django 3.2.5 on 2021-07-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0010_auto_20210712_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='Rec_Type',
            field=models.CharField(default='In', max_length=3),
        ),
        migrations.AlterField(
            model_name='records',
            name='Rec_Name',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
