# Generated by Django 3.2.5 on 2021-07-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0011_auto_20210712_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_version', models.PositiveIntegerField(default=1)),
                ('simulation_start_date', models.CharField(default='01 2020', max_length=7)),
                ('simulation_end_date', models.CharField(default='02 2020', max_length=7)),
            ],
        ),
    ]
