# Generated by Django 3.2.5 on 2021-07-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0012_mysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fam_name', models.CharField(max_length=80)),
                ('Rec_Name', models.CharField(default='Name', max_length=50)),
                ('Eve_Name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='c_Familys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fam_name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='c_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fam_name', models.CharField(max_length=80)),
                ('Rec_Name', models.CharField(default='Name', max_length=50)),
                ('Rec_Type', models.CharField(default='In', max_length=3)),
                ('Start_Date', models.CharField(default='mm_yyyy', max_length=20)),
                ('End_Date', models.CharField(default='mm_yyyy', max_length=20)),
                ('Value', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
