# Generated by Django 3.2.5 on 2021-07-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0014_auto_20210722_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_events',
            name='Rec_Type',
            field=models.CharField(default='In', max_length=3),
        ),
    ]
