# Generated by Django 3.2.5 on 2021-07-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0016_c_records_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='Family',
        ),
        migrations.AlterField(
            model_name='c_records',
            name='End_Date',
            field=models.CharField(default='mm yyyy', max_length=20),
        ),
        migrations.AlterField(
            model_name='c_records',
            name='Start_Date',
            field=models.CharField(default='mm yyyy', max_length=20),
        ),
        migrations.DeleteModel(
            name='Familys',
        ),
        migrations.DeleteModel(
            name='Records',
        ),
    ]
