# Generated by Django 3.2.5 on 2021-07-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0018_c_familys_fam_name1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_familys',
            name='Fam_name1',
        ),
    ]
