# Generated by Django 3.2.5 on 2021-07-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0019_remove_c_familys_fam_name1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MySettings',
        ),
    ]
