# Generated by Django 3.2.5 on 2021-07-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FuturePlanning', '0020_delete_mysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_version', models.PositiveIntegerField(default=1)),
                ('simulation_start_date', models.CharField(default='01 2020', max_length=7)),
                ('simulation_end_date', models.CharField(default='02 2020', max_length=7)),
                ('record_type1', models.CharField(default='In', max_length=7)),
                ('record_type2', models.CharField(default='Expanse', max_length=7)),
                ('record_type3', models.CharField(default='Savings', max_length=7)),
                ('record_type4', models.CharField(default='Loans', max_length=7)),
            ],
        ),
    ]
